# This is a basic workflow that is manually triggered

name: Ecosia Master

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - name
      
env:
  GIT_SHA: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  GIT_PAT: ${{ secrets.GIT_PAT }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  EXPLORER_IMAGE: odytrice/nomad-explorer
  BITCOIN_API_IMAGE: odytrice/nomad-bitcoin-api
  BITCOIN_INDEXER_IMAGE: odytrice/nomad-bitcoin-indexer
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
