name: Production
on:
  push:
    branches:
    - master

env:
  GIT_SHA: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  # GIT_PAT: ${{ secrets.GIT_PAT }}


jobs: 
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Prescript 
      run: |
        apk add --no-cache groff less bash jq curl py-pip tzdata
        pip install awscli

    - name: Push to repository
      run: |
        $(aws ecr get-login --no-include-email --region us-east-2)
        docker build -t 265311748595.dkr.ecr.us-west-2.amazonaws.com/ecosia:$GIT_SHA .
        docker push 265311748595.dkr.ecr.us-east-2.amazonaws.com/fmscapproval:$GIT_SHA
